name: "🐛 Bug Report"
description: "If something isn't working as expected 🤔."
title: "[Bug]: "
labels: ["i: bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

  - type: checkboxes
    id: input1
    attributes:
      label: "💻"
      options:
        - label: Would you like to work on a fix?
      
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear and concise description of the current behavior.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of you would expect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible solution
      description: "If you have suggestions on a fix for the bug."

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here. Or a screenshot if applicable."