{{/*
    Helper templates for prefect-agent
    Includes:
      name
      nameField
      matchLabels
      commonLabels
      serviceAccountName
  */}}
{{/*
prefect-agent.name:
    Define a name for the application as {chart-name}
    Name fields are limited to 63 characters by the DNS naming spec
*/}}
{{- define "prefect-agent.name" -}}
{{ .Values.nameOverride | default .Chart.Name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{/*
prefect-agent.nameField(component):
    Populates a configuration name field's value by as {release}-{component} or
    {release}-{chart}-{component} depending on the value of 'includeChartNameInComponents'
    Request the component name to be passed by adding to the context e.g.
    include "prefect-agent.nameField (merge (dict "component" "apollo") .)
    Name fields are limited to 63 characters by the DNS naming spec
*/}}

{{- define "prefect-agent.nameField" -}}
{{- $componentName := .component -}}
{{- if .Values.includeChartNameInComponents -}}
{{- $chartName := include "prefect-agent.name" . -}}
{{ printf "%s-%s-%s" .Release.Name $chartName $componentName | trunc 63 | trimSuffix "-" }}
{{- else -}}
{{ printf "%s-%s" .Release.Name $componentName | trunc 63 | trimSuffix "-" }}
{{- end -}}
{{- end }}
{{/*
prefect-agent.matchLabels:
    Provides K8s selection labels typically for use within the `spec` section
    Includes "name" and "instance"
    "component" is not provided and should be added by the component
*/}}
{{- define "prefect-agent.matchLabels" -}}
app.kubernetes.io/name: {{ include "prefect-agent.name" . }}
app.kubernetes.io/instance:  {{ .Release.Name }}
{{- end -}}
{{/*
prefect-agent.commonLabels:
    Provides common K8s labels, including "prefect-agent.matchLabels"
    typically for use within the top-level metadata
    Includes "chart", "version", and "managed-by" as well as the match 
    labels generated by "prefect-agent.matchLabels"
    "component" is not provided and should be added by the component
*/}}
{{- define "prefect-agent.commonLabels" -}}
{{ include "prefect-agent.matchLabels" . }}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
{{/*
prefect-agent.serviceAccountName:
    Create the name of the service account to use
*/}}
{{- define "prefect-agent.serviceAccountName" -}}
{{- if .Values.serviceAccount.create -}}
    {{- $createName := include "prefect-agent.nameField" (merge (dict "component" "serviceaccount") .) -}}
    {{- .Values.serviceAccount.name | default $createName -}}
{{- else -}}
    {{- .Values.serviceAccount.name | default "default" -}}
{{- end -}}
{{- end -}}
{{/*
env-unrap:
    Converts a nested dictionary with keys `prefix` and `map`
    into a list of environment variable definitions, where each
    variable name is an uppercased concatenation of keys in the map
    starting with the original prefix and descending to each leaf.
    The variable value is then the quoted value of each leaf key.
*/}}
{{- define "env-unwrap" -}}
{{- $prefix := .prefix -}}
{{/* Iterate through all keys in the current map level */}}
{{- range $key, $val := .map -}}
{{- $key := upper $key -}}
{{/* Create an environment variable if this is a leaf */}}
{{- if ne (typeOf $val | toString) "map[string]interface {}" }}
- name: {{ printf "%s__%s" $prefix $key }}
value: {{ $val | quote }}
{{/* Otherwise, recurse into each child key with an updated prefix */}}
{{- else -}}
{{- $prefix := (printf "%s__%s" $prefix $key) -}}
{{- $args := (dict "prefix" $prefix "map" $val)  -}}
{{- include "env-unwrap" $args -}}
{{- end -}}
{{- end -}}
{{- end -}}